### ISSUE TITLE
Issue with running example data

### ISSUE THREAD

**Issue by Xinyu-Sun** [mancusolab/sushie#41]
Hello,

Thanks for developing this amazing software! I followed the instructions to install the package into a conda environment with `Python 3.10.14` on a Linux system. The installation seems to be successful, but when I run the "Get Started with Example" command:
```
cd ./data/
sushie finemap --pheno EUR.pheno AFR.pheno --vcf vcf/EUR.vcf vcf/AFR.vcf --covar EUR.covar AFR.covar --output ./test_result
```
I encounter the following error message:
```
===================================
             SuShiE v0.15.post1.dev3+g97cb3ad             
===================================
sushie finemap
        --pheno EUR.pheno
                AFR.pheno
        --vcf vcf/EUR.vcf
              vcf/AFR.vcf
        --covar EUR.covar
                AFR.covar
        --output ./test_result

Starting log...
[2024-06-15 00:27:34 - INFO] Detect phenotypes for Trait from 2 ancestries.
[2024-06-15 00:27:34 - INFO] Detect genotype data in vcf format.
[2024-06-15 00:27:34 - INFO] Detect covariates data.
[2024-06-15 00:27:34 - INFO] Fine-mapping finishes for Trait, and thanks for using our software. For bug reporting, suggestions, and comments, please go to https://github.com/mancusolab/sushie.
Traceback (most recent call last):
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/cli.py", line 1014, in run_finemap
    rawData = io.read_data(
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/io.py", line 116, in read_data
    bim, fam, bed = geno_func(geno_paths[idx])
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/io.py", line 221, in read_vcf
    var.gt_types = jnp.where(var.gt_types == 3, jnp.nan, var.gt_types)
AttributeError: attribute 'gt_types' of 'cyvcf2.cyvcf2.Variant' objects is not writable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxs410/.conda/envs/sushie/bin/sushie", line 8, in <module>
    sys.exit(run_cli())
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/cli.py", line 1641, in run_cli
    return _main(sys.argv[1:])
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/cli.py", line 1635, in _main
    args.func(args)
  File "/home/xxs410/.conda/envs/sushie/lib/python3.10/site-packages/sushie/cli.py", line 1053, in run_finemap
    traceback.format_exception(
TypeError: format_exception() got an unexpected keyword argument 'etype'
```

I believe the issue is specific to the VCF format genotype data, as the error does not occur when I replace `--vcf` with `--plink`.

Thanks in advance!

Xinyu

**Comment by zeyunlu** [comment]
Sorry, I didn't see this until now.

Nice catch! Will fix this in next version!
